import type { Metadata } from "next";

import "./globals.css";
import ThemeToggle from "./_components/toggletheme";
import Footer from "./_components/footer";
import LogoutButton from "./_components/logout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <ThemeToggle />
        <LogoutButton />
        {children}
        <Footer />
      </body>
    </html>
  );
}
